### ISSUE TITLE
Feature request: automatic delaying/postponing updates

### ISSUE THREAD

**Issue by oldrup** [audrasjb/wp-autoupdates#13]
While I like automatic updates, and already uses several plugins from WordPress.org on not so prominent sites, I suggest you make it an option to delay/postpone updates for a while or maybe schedule them to specific days og time of day.

a) For instance, I'd really prefer NOT to have major updates of themes and plugins being applied friday 4pm ;) Maybe auto-updated could be appled every tuesday at 9am where there are fewest visitors on my sites, and I'm available to fix any issues. Just an example, hope it makes sense.

b) Sometimes, feature updates of community created plugins introduce new bugs. Both as a plugin consumer, and probably as a plugin author, I'd prefer updates to "drip release". Releasing a buggy update, and having it auto-install on millions of sites right after release, does not seem to be a ideal situation for neither the users nor the developer.

c) Maybe updates could be tagged as feature updates, bugfixes and critical security updates, and the level of automation could differ accordingly?

In any case - its a great feature and I'm sure it will help improving the security of WordPress installations. Thanks for making this a part of WordPress core.

**Comment by audrasjb** [comment]
Hi @oldrup 

I think this features are not core territory but rather plugin territory.
But in my opinion, those are great question and I think WordPress Core should add some hooks to help other plugins that may want to add such an extra option.

Thanks a lot for raising that :-)

**Comment by jeffpaul** [comment]
_Closing in favor of migrated issue: https://github.com/WordPress/auto-updates/issues/4_
