### ISSUE TITLE
Proposal for new features

### ISSUE THREAD

**Issue by NicolasKulka** [audrasjb/wp-autoupdates#14]
Je crois qu’il est déjà prévu d’intégrer le fait de prévenir les personnes par mail des mises à jours disponible, mais est-ce qu’il est prévu de pouvoir configurer ce mail natif ou hook ?

2ème fonctionnalité, prévoir auto-update mais pas immédiat mettre des choix de jours par exemple mettre à jour au bout de 7, 15 et 30 jours ?

**Comment by audrasjb** [comment]
Hi @NicolasKulka, 

Thanks for your comment! Let's translate it into English :)

> I believe there are already plans to include email notifications about available updates, but are there plans to be able to configure this native mail or hook?

Yes, this is already handled in ticket #48850 in WordPress Core Trac, but I have not yet started to handle this feature in the Feature Plugin. Stay tuned! 😉 

> 2nd feature, provide for auto-update but not immediate put choices of days for example update after 7, 15 and 30 days?

I think this is definitely plugin territory. But the Core feature may propose hooks for plugins developers so they could eventually create this feature on their side. 
Also mentioned in issue #13. 

Cheers,
Jb

**Comment by jeffpaul** [comment]
_Closing in favor of migrated issue: https://github.com/WordPress/auto-updates/issues/5_
