### ISSUE TITLE
Plugin/theme auto update already on by earlier filter

### ISSUE THREAD

**Issue by knutsp** [audrasjb/wp-autoupdates#16]
When `add_filter( 'auto_update_{plugin|theme}', '__return_true', 1 );` so that $update is already true, wp-autoupdates should leave it as is for backwards compatibility with plugins. This should be detected so that there is no "Enable" action button, and probably no "Disable".

It could be nice to be able to override this by allowing "Disable", though.

I use "Advanced Automatic Updates" by pento and I expect it to still work without intervention and indicated correctly in the plugins list.

**Comment by knutsp** [comment]
"Advanced Automatic Updates" with plugins checked has no effect on the list now. I still think this should show all plugins as enabled, but with no visible disable action, or subsidiarly disable action just to have no effect.

**Comment by jeffpaul** [comment]
_Closing in favor of migrated issue: https://github.com/WordPress/auto-updates/issues/6_
