### ISSUE TITLE
Add a warning on specific plugins which you may not want to automatically update

### ISSUE THREAD

**Issue by lukecav** [audrasjb/wp-autoupdates#19]
If a plugin like **WooCommerce** is enabled to be automatically updated in the UI then add some notification or warning that automatically updating that specific plugin about other issues it might cause if paid plugins for WooCommerce where also not updated as well the active theme. It could result in a broken WooCommerce store.

**Comment by audrasjb** [comment]
Hi @lukecav ,

The only thing we can do is to propose the auto-update feature as manual opt-in. The good news is that it's already the case with this Feature plugin :)

To be clear, we can't check that automatically as it depends on the related plugins. That's why it's going to be a manual opt-in 😉
