### ISSUE TITLE
Major / Minor releases or Semvar

### ISSUE THREAD

**Issue by asadkn** [audrasjb/wp-autoupdates#23]
WordPress core only auto-updates to minor releases. The same concept should also be available to plugins and themes.

As a plugin or theme developer, we know there are likely to be breaking changes, once in a while,  where user attention is warranted prior to update.

Was something like Semvar or auto-updates to minor versions only discussed somewhere?

**Comment by audrasjb** [comment]
Hello @asadkn and thank you for sharing your thoughts!

Unfortunately, this is not possible as plugin authors are free to use the versioning system they want. Some plugin authors use SemVer, others use something more close to WP Core versioning system (which is not SemVer), and others even use the date of the release as the version number.

For example see Block Bad Queries (100K+ active installations): https://wordpress.org/plugins/block-bad-queries/#developers

Thanks for the idea, by the way 😉 
Cheers,
Jb

**Comment by audrasjb** [comment]
Closing the issue as it's not possible to handle that properly.
