### ISSUE TITLE
ensure that "the right thing" happens with plugins that are symlink'd

### ISSUE THREAD

**Issue by pbiron** [audrasjb/wp-autoupdates#27]
Currently, core can have problems when updating plugins (and themes) that are synlink'd.

Here are a couple of related core Trac tickets:

- https://core.trac.wordpress.org/ticket/29408
- https://core.trac.wordpress.org/ticket/36710

I think that the problem should be fixed in core (e.g., 36710) rather than in this feature plugin and/or its merge proposal (e.g., by checking whether the plugin/theme is a symlink and skipping the enable/disable actions, etc), but wanted to open this issue so that it doesn't get lost.

**Comment by jeffpaul** [comment]
_Closing in favor of migrated issue: https://github.com/WordPress/auto-updates/issues/7_
