### ISSUE TITLE
Forcing update while scheduled doesn't remove scheduled update

### ISSUE THREAD

**Issue by bookdude13** [audrasjb/wp-autoupdates#28]
I was testing this out using the Query Monitor plugin. Repro:
- Install version [3.5.1](https://downloads.wordpress.org/plugin/query-monitor.3.5.1.zip) from a zip file
- Enable auto-updates
- The update option is still available to force the update. Click it, and notice that the scheduled update appears to still linger

![still scheduled after forced update](https://user-images.githubusercontent.com/6414232/75633526-c4871380-5c05-11ea-95e6-ad5de7383ad7.PNG)

**Comment by audrasjb** [comment]
Thanks for catching this. Let's address this when possible 👍
