### ISSUE TITLE
Deleting plugin doesn't remove auto-update preference

### ISSUE THREAD

**Issue by bookdude13** [audrasjb/wp-autoupdates#29]
Not sure if this is good or bad. Auto-update is set to enabled on second install. Reproduction steps:
- Install plugin (I did from file; untested with other means)
- Enable auto-updates
- Remove it using Delete link in left column
- At this point you can refresh, log out, or do nothing - it doesn't matter
- Install the plugin again (again, I did from file. Different versions still had this bug happen)
- Note that auto-updates are enabled

**Comment by pbiron** [comment]
I've noticed this in my testing as well.

I think that we can hook into the `deleted_plugin`  action and remove the deleted plugin from the `wp_auto_update_plugins` site option.   I'll do a PR for that when I get a chance (unless someone beats me to it :-).

**Comment by bookdude13** [comment]
I'll take a swing at it tonight :)

**Comment by pbiron** [comment]
> I'll take a swing at it tonight :)

he took the hint :-)  Thanx!

**Comment by bookdude13** [comment]
Thanks for the outline of what to do; that was my first time dealing directly with hooks in plugins, and it was a great way to get exposed!

**Comment by audrasjb** [comment]
Yeah this should be fixed. Milestoning for 0.2
