### ISSUE TITLE
Automatically rollback to previous version if fatal errors detected after update.

### ISSUE THREAD

**Issue by danieliser** [audrasjb/wp-autoupdates#31]
The one thing that makes this safe to use on production sites seems to be missing.

If a new plugin update all of a sudden causes a fatal error I assume the WP core error detection and notifications will kick in, but this is not ideal for something that is running on autopilot.

I'd suggest something along the lines of what the [Easy Theme & Plugin Upgrades](https://wordpress.org/plugins/easy-theme-and-plugin-upgrades/) plugin does and backup the current copy of the plugin/theme to a zip in the uploads folder.

Further if an error is detected during the update process or within a defined period of time shortly after, the older version should be restored and a notice sent about the error information to the admin.

1. Backup existing version to zip file in uploads folder.
2. Install new version.
3. Set flag/transient that it was _recently_updated.
4. Listen for errors until that flag expires.
5. If an error occurs:
  - email admins relevant info
  - revert to previous version
  - disable auto updates for this plugin until reviewed.

**Comment by audrasjb** [comment]
Hi,

Thank you for raising this but it's not in the scope of the Core feature for the moment. Let's discuss this in the next few weeks but I really feel we're out of the scope and it will remains plugin’s territory. But I prefer to keep the issue open so it could be discussed as we're in the earlier stage of the feature.

Thanks

**Comment by jeffpaul** [comment]
_Closing in favor of migrated issue: https://github.com/WordPress/auto-updates/issues/9_
