### ISSUE TITLE
status links count off if all_plugins filter has been used.

### ISSUE THREAD

**Issue by timnashcouk** [audrasjb/wp-autoupdates#50]
line 354 wp-autoupdates.php
`$wp_autoupdate_plugins = array_intersect( $wp_autoupdate_plugins, array_keys( get_plugins() ) );`
The get_plugins should be prefiltered via the all_plugins filter, otherwise plugins that have been filtered will appear in the count, but not on the update page and will show different totals to the other status links

`
$all_plugins = apply_filters( 'all_plugins', get_plugins() );
$wp_autoupdate_plugins = array_intersect( $wp_autoupdate_plugins, array_keys( $all_plugins ) );
`

**Comment by pbiron** [comment]
Thanx @timnashcouk you are absolutely right.

Would you like to open a PR with a fix?
