### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rodolphebertozzo** [audrasjb/wp-autoupdates#51]
Do you plan in the coming months to make the plugin also take care of automatic updates for the Wordpress CMS?
Also, how to enable automatic update for themes?

**Comment by audrasjb** [comment]
Hello,
It depends on the progress made on Plugins & Themes auto-udpates, but yes, WordPress Core (opt-in) auto-updates are in the roadmap, and currently slated for WordPress 5.6.

For reference: https://make.wordpress.org/updates/2020/03/06/update-progress-on-goals/

**Comment by audrasjb** [comment]
> Also, how to enable automatic update for themes?

This in not in place for the moment, it should ship with version 0.4.0 of the plugin :)

**Comment by rodolphebertozzo** [comment]
Thank you for your response. Congratulations for your work, keep up the good work and listen to your users!

**Comment by audrasjb** [comment]
You're most welcome @rodolphebertozzo ! 🙌
