### ISSUE TITLE
The notices that auto-update is "scheduled in X days" are incorrect if cron job is overdue

### ISSUE THREAD

**Issue by pbiron** [audrasjb/wp-autoupdates#55]
The code in `wp_autoupdates_add_plugins_autoupdates_column_content()` and `wp_autoupdates_enqueues()` assumes that the value returned by `wp_next_scheduled( 'wp_version_check' )` is always in the future.

If the `wp_version_check` cron job is overdue for any reason (e.g., `defined( 'DISABLE_WP_CRON', true );` in wp-config.php), then the "scheduled in X days" text is incorrect.

For example, on one test site I have WP_Cron disabled, and the cron job is overdue by 2 days (should have run 2 days ago), but the text suggests it is schedule for 2 days from now.

![plugins](https://user-images.githubusercontent.com/3824560/76544857-5edd2780-644e-11ea-922d-747986b9776f.png)

![update-core](https://user-images.githubusercontent.com/3824560/76544878-68ff2600-644e-11ea-8e9c-51f0abc56a82.png)

**Comment by afragen** [comment]
I actually have code for this in GitHub Updater.

https://github.com/afragen/github-updater/blob/9fcaee60106741e297ff22ddd0d21529c8354e32/src/GitHub_Updater/Traits/GHU_Trait.php#L627-L634

```php
public function is_cron_overdue( $cron, $timestamp ) {
	$overdue = ( ( time() - $timestamp ) / HOUR_IN_SECONDS ) > 24;
	if ( $overdue ) {
		$error_msg = esc_html__( 'There may be a problem with WP-Cron. A GitHub Updater WP-Cron event is overdue.', 'github-updater' );
		$error     = new \WP_Error( 'github_updater_cron_error', $error_msg );
		Singleton::get_instance( 'Messages', $this )->create_error_message( $error );
	}
}
```
