### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rodolphebertozzo** [audrasjb/wp-autoupdates#61]
If I understood correctly, the automatic update feature for themes and plugins should be implemented in Wordpress version 5.5.
Wordpress auto updates will therefore be optimized, operational and ready to be installed on different sites by then?
Or there will be no need for a plugin (these features will be directly integrated into the core of Wordpress) and in this case, what would become of Wordpress auto-updates?

**Comment by audrasjb** [comment]
Hello,
Yes, as an official _Feature Plugin_, this plugin is meant to be integrated into WordPress Core, just like [Health Check](https://wordpress.org/plugins/health-check/).
Once it's merged, this plugin is likely to be used for the work on Core major versions auto-updates, but there is no plan for this at the moment.

**Comment by jeffpaul** [comment]
_Closing in favor of migrated issue: https://github.com/WordPress/auto-updates/issues/11_
