### ISSUE TITLE
Option value empty, not possible to enable aut update for any plugin

### ISSUE THREAD

**Issue by knutsp** [audrasjb/wp-autoupdates#63]
My option wp_auto_update_plugins value was suddenly empty, in version 0.3.0. I have had the plugin installed since first released on wporg.
In that state i was not possible to Enable plugins to auto update. PHP warnings about value not an array or iterable.
Bug: Empty value should never go into this option.
Safe guard: Empty value, or maybe any non-array, should not stop the plugin from Enable new plugins
Themes: Possible same issues there.

Slack thread: https://wordpress.slack.com/archives/CULBN711P/p1584551222179500

**Comment by audrasjb** [comment]
Thanks for opening the issue @knutsp !
Milestoning to 0.3.1 👍

**Comment by pbiron** [comment]
After looking through the 0.3.0 code, I don't see an obvious way the value of the site option could have ended up as an empty string.

In general, core does **not** check that the type of the value returned from a DB query is what it was expecting, altho there are a some cases where values that are expected to be arrays are cast to array...just to be sure.

So, to prevent a corrupted value from impacting the ability to enable/disable **new** auto-updates we could replace all occurrences of 
```
$variable = get_site_option( 'wp_auto_update_plugins', array() );
```

with

```
$variable = (array) get_site_option( 'wp_auto_update_plugins', array() );
```
Before doing a PR for this, I'll wait a little to see if anyone else has any other ideas.

**Comment by bookdude13** [comment]
That seems like a sane approach to me. However, is there any value that would cause the cast to fail? That would be replacing one problem with another.

**Comment by pbiron** [comment]
AFAIK, casting to an array can't "fail" in PHP :-)

See [Converting to array](https://www.php.net/manual/en/language.types.array.php#language.types.array.casting) in the PHP manual for the rules that cover casting to an array.

For example:

```
// these cases shouldn't cause a problem, because all of the
// in_array( $plugin, $wp_auto_update_plugins, true ) tests in the code will fail, as they should
$value = (array) '';
// $value is now the same as array( '' )
$value = (array) null;
// $value is now the same as array()
$value = (array) 123;
// $value is now the same as array( 123 )
$value = (array) true;
// $value is now the same as array( true )

// this is where it gets interesting :-)

// this case also shouldn't cause a problem, because if such a value
// were ever read from the DB I'd think we want in_array( $plugin, $wp_auto_update_plugins, true ) to succeed
$value = (array) 'my-plugin/my-plugin.php';
// $value is now the same as array( 'my-plugin/my-plugin.php' )

// this one I'm not so sure of.  Any thoughts?
class My_Class {
   public $prop = 'my-plugin/my-plugin.php'; 
}
$value = (array) new My_Class();
// $value is now the same as array( 'prop' => 'my-plugin/my-plugin.php' )
```

**Comment by bookdude13** [comment]
Haha, I should've checked the docs before commenting. Still not very familiar with PHP :-) My concern was with null/empty string values, but those seem handled well. Any weird value gets thrown into an array and won't match a valid plugin, so that seems fine by me!

**Comment by knutsp** [comment]
I'm not fan of blindly casting untrusted values to array, as it may introduce stray garbage elements that will never go away. Best, IMHO:
`$variable = get_site_option( 'wp_auto_update_plugins', array() );`
`$variable = is_array( $variable) ? $variable : array(); // Only arrays can be trusted, else reset it`
By this you **know** that any illegal option value (not array) will result in an empty array.

**Comment by pbiron** [comment]
@knutsp I kind of agree, and my first impulse was to add a couple of wrapper functions to get/update the site option that checked whether it was an array and if not set it to `array()`, just as you suggest.  

But, as mentioned, that's not generally how the rest of core is coded...and this will be merged into core, my suggestion is to follow the core coding practices here as well.

I'll let @audrasjb make the final call.

**Comment by jeffpaul** [comment]
_Closing in favor of migrated issue: https://github.com/WordPress/auto-updates/issues/13_
