### ISSUE TITLE
Move the repository to WordPress.org GitHub account

### ISSUE THREAD

**Issue by jeffpaul** [audrasjb/wp-autoupdates#64]
The repo is currently within @audrasjb's personal account, this issue exists to move it within the @wordpress org.  We'll want to ensure we closely review access levels from the existing repo to the new repo to confirm all levels are truly necessary.

**Comment by peterwilsoncc** [comment]
From memory, a [WordPress organisation owner](https://github.com/orgs/WordPress/people?query=role%3Aowner) will need to be made an admin of this repo to allow them to move the repo across to the WordPress org.

**Comment by jeffpaul** [comment]
Closing this issue now that https://github.com/WordPress/auto-updates exists and we're actively working to migrate from https://github.com/audrasjb/wp-autoupdates to https://github.com/WordPress/auto-updates.
