### ISSUE TITLE
Use the CSS class `notice-success` instead of  `updated`

### ISSUE THREAD

**Issue by afercia** [audrasjb/wp-autoupdates#7]
Re: the admin notices, the CSS class `updated` is legacy and _de facto_ deprecated as well as the `error` one.

Admin notices CSS classes work in a way that there's a base `notice` class and modifiers like `notice-success`, `notice-warning`, `notice-info`, `notice-error`, etc.

For "success" notices, the recommended usage is `notice notice-success` so this part should be updated accordingly to the established core practices:

https://github.com/audrasjb/wp-autoupdates/blob/cf5286b7e9629d1c5a4de5fdecff96404a9a248f/wp-autoupdates.php#L296-L301

**Comment by afercia** [comment]
Reference: https://core.trac.wordpress.org/changeset/30505

**Comment by audrasjb** [comment]
Nice catch, thank you!
